<?php /*
header('Content-Type: text/html; charset=utf-8', true);

$id = '778';
// $resp = file_get_contents('http://test.local/api/api.php?id='. $id);
$resp = file_get_contents('http://api.local/orders/'. $id);
$data = json_decode($resp, true);

if($data['status'] == '200'){

  // echo '<pre>';
  // var_dump($data['data']);
  // echo '</pre>';

  echo 'status  : ' . $data['status'] . '</br>';
  echo 'message : ' . $data['message'] . '</br>';

  foreach ($data['data'] as $key => $value) {
    if (!is_int($key)  ) {
      echo $key . ' : ' . $value . '</br>';
    }
  }
}else{
    echo 'asas: '.$data['error'];
}

// var_dump($data);
*/
// вывести дату с расшифровкой
// SELECT FROM_UNIXTIME(created),created FROM orders WHERE offer_owner = 202
// вывод за 2 последних дня: http://api.local/get/orders?hash=222&c=(1456926962,1457113441)
//http://api.local/get/orders?hash=222&c=(1456926962,1457113441)&limit=4
//http://api.local/get/orders?hash=222&f=(status:2)&c=(1456926962,1457113441)
//http://api.local/get/orders?hash=222&f=(status:2,status2:2)&c=(1456926962,1457113441)
//http://api.local/get/orders?hash=222&f=(status:2,status2:2.country_code:ru)&c=(1456926962,1457113441)
//http://api.local/get/orders?hash=222&f=(status:2)&c=(1456926962,1457113441)&o=(364902,364919,364971)
//http://api.local/get/orders?hash=222&f=(status:2)&c=(1456926962,1457113441)&o=(364902,364919,364971)&id=(575,576)

//нужно ли прописывать?
//http://api.local/get/orders?hash=222&f=(status:2,first_name:%D0%98%D0%B3%D0%BE%D1%80%D1%8C) - нельзя по русски
//http://api.local/get/orders?hash=222&f=(status:2,ip:178.93.133.95) - не работает поиск по ip
//http://api.local/get/orders?hash=222&f=(commission:100) - не работает поиск по комисии

/**
 *
 */

 $input = array(
 	'hash'        => '123',
 	'status'      => 3,
 	'oid'         => 45,
 	'id'          => 879,
 	'status2'     => 8,
 	'comment'     => 'тестовый комментарий'
 );

 $url = 'http://api.local/set/status';
 $json = json_encode($input);
 $headers = array(
   'Content-Type: application/json',
   'Content-Length: ' . strlen($json),
 );

 $ch = curl_init($url);
 curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
 curl_setopt($ch, CURLOPT_POSTFIELDS, $json);
 curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
 curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

 $result = curl_exec($ch);
 var_dump($result);
